### ISSUE TITLE
Install broken

### ISSUE THREAD

**Issue by ando-shah** [michaeltrs/DeepSatModels#16]
Using the conda environment from `deepsatmodels_env.yml` followed by `conda install pytorch torchvision torchaudio cudatoolkit=10.1 -c pytorch-nightly`, followed by running the training command leads to the following error:

```
Traceback (most recent call last):
  File "train_and_eval/segmentation_training_transf.py", line 5, in <module>
    import torch
  File "/opt/conda/envs/deepsatmodels/lib/python3.8/site-packages/torch/__init__.py", line 364, in <module>
    from torch._C import *  # noqa: F403
ImportError: /opt/conda/envs/deepsatmodels/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: cblas_gemm_bf16bf16f32
```

Upgrading the pytorch and torchvision doesnt seem to help.
CUDA version 12.4

**Comment by vhvkhoa** [comment]
This command works for me:
```conda install pytorch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 cudatoolkit=10.2 -c pytorch```
